apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: cloud-computing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
        - containerPort: 3001
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
          value: "5s"
        - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
          value: "/etc/grafana/provisioning/dashboards/guestbook-dashboard.json"
        - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_UID
          value: "guestbook"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-dashboard-provisioning
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-datasource
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboard-provisioning
        configMap:
          name: grafana-dashboard-provisioning
      - name: grafana-datasource
        configMap:
          name: grafana-datasource 