apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: cloud-computing
  labels:
    grafana_datasource: "true"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
      editable: true 