apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tubesfix

spec:
  type: ClusterIP
  selector:
  app: frontend
  ports:  
    - protocol: TCP
      port: 8080
      targetPort: 8080
