apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cloud-computing
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: backend 