apiVersion: apps/v1
kind: ingress
metadata:
  name: frontend-ingress
  namespace: tubesfix

spec:
  rules:
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080
      http:
        paths:    
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 3000
        
