apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cloud-computing
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
  type: ClusterIP 