apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_PATH
          value: "/app/data/guestbook.sqlite"   # contoh path file db
        volumeMounts:
        - name: sqlite-data
          mountPath: /app/data                   # path tempat SQLite file di container
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /entries                      # endpoint API health check atau list entries
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /entries
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: sqlite-data
        persistentVolumeClaim:
          claimName: sqlite-pvc                # sesuaikan dengan nama PVC yang kamu buat
