apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tubesfix

spec:
  type: ClusterIP
  selector:
    app: backend         # indentasi diperbaiki (harus 2 spasi di bawah selector)
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
